matrix:

- name: text
  sources:
  - 'xml-files/extracted_text_from_xml.txt'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - 'custom-dictionary.txt'
  default_encoding: cp1252
  pipeline:
  - pyspelling.filters.text:
      convert_encoding: utf-8

- name: markdown
  sources:
  - '**/*.md'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - 'custom-dictionary.txt'
  pipeline:
  - pyspelling.filters.markdown:

- name: python
  sources:
  - 'python-files/**/*.py'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - 'custom-dictionary.txt'
  pipeline:
  - pyspelling.filters.python:
      # the following options are 'true' by default: 'comments', 'docstrings', and 'decode_escapes'

# - name: xml
#   sources:
#   - 'xml-files/*.xml'
#   aspell:
#     lang: en
#   dictionary:
#     wordlists:
#     - 'custom-dictionary.txt'
#   pipeline:
#   - pyspelling.filters.xml:
#       comments: false
#       captures:
#       - :matches(value, name, description, label)
