name: Test
on:
  pull_request:
  push:

jobs:
  spell-check:
    name: Spell check code and documents

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        sudo apt-get install --assume-yes aspell aspell-en
        python -m pip install --upgrade pip
        pip install pyspelling
    - name: Run spell-check
      run: pyspelling